apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: pigops.pigops.gkarthiks.io
spec:
  group: pigops.gkarthiks.io
  names:
    kind: Pigops
    listKind: PigopsList
    plural: pigops
    singular: pigops
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          type: object
        status:
          type: object
  version: v1alpha1
