// +build !ignore_autogenerated

// Code generated by openapi-gen. DO NOT EDIT.

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/gkarthiks/pig-operator/pig-operator/pkg/apis/pigops/v1alpha1.Pigops":       schema_pkg_apis_pigops_v1alpha1_Pigops(ref),
		"github.com/gkarthiks/pig-operator/pig-operator/pkg/apis/pigops/v1alpha1.PigopsSpec":   schema_pkg_apis_pigops_v1alpha1_PigopsSpec(ref),
		"github.com/gkarthiks/pig-operator/pig-operator/pkg/apis/pigops/v1alpha1.PigopsStatus": schema_pkg_apis_pigops_v1alpha1_PigopsStatus(ref),
	}
}

func schema_pkg_apis_pigops_v1alpha1_Pigops(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "Pigops is the Schema for the pigops API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/gkarthiks/pig-operator/pig-operator/pkg/apis/pigops/v1alpha1.PigopsSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/gkarthiks/pig-operator/pig-operator/pkg/apis/pigops/v1alpha1.PigopsStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/gkarthiks/pig-operator/pig-operator/pkg/apis/pigops/v1alpha1.PigopsSpec", "github.com/gkarthiks/pig-operator/pig-operator/pkg/apis/pigops/v1alpha1.PigopsStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_pigops_v1alpha1_PigopsSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "PigopsSpec defines the desired state of Pigops",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_pigops_v1alpha1_PigopsStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "PigopsStatus defines the observed state of Pigops",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}
